#!/usr/bin/env python
import csv
import parser
import re
from pathlib import Path
from sys import argv, platform
from threading import Thread
from time import sleep

import mutagen  # for getting song duration

if platform != "win32":
    import readline

import pygame
from pygame import mixer
from pygame.mixer import music

import macros
import smp_queue as q
from macros import macro
from settings import Settings, config, reload_cfg
from smp_common import ac_songs, autocomplete, gen_files, timestamp, type_converter
from smp_help import ihelp, command
from smp_queue import Player, queue

CONFIG_DIR = Path("~/.config/smp/").expanduser()
CONFIG_PATH = CONFIG_DIR / "smp.conf"
SCRIPTS_DIR = CONFIG_DIR / "scripts"
SUPPORTED_TYPES = ["mp3", "ogg", "wav", "flac", "opus"]
CMDS = {
    "config": lambda *args: config(*args),
    "delete": lambda *args: delete(*args),
    "exec": lambda *args: exec_scripts(*args),
    "exit": lambda *args: smp_exit(*args),
    "find": lambda *args: find(*args),
    "forward": lambda *args: seek_relative(*args, forward=True),
    "help": lambda *args: ihelp(*args, player=Player),
    "list": lambda *args: ls(*args),
    "loop": lambda *args: loop(*args),
    "ls": lambda *args: ls(*args),
    "macro": lambda *args: macro(*args),
    "pause": lambda *args: pause(*args),
    "play": lambda *args: play(*args),
    "queue": lambda *args: queue(*args),
    "quit": lambda *args: smp_exit(*args),
    "rename": lambda *args: rename(*args),
    "repeat": lambda *args: repeat(*args),
    "rewind": lambda *args: seek_relative(*args),
    "seek": lambda *args: seek_absolute(*args),
    "stop": lambda *args: stop(*args),
    "time": lambda *args: time(*args),
    "unpause": lambda *args: unpause(*args),
    "volume": lambda *args: volume(*args),
}


@command(Player, "exec")
def exec_scripts(*args):
    for arg in args:
        if not (SCRIPTS_DIR / arg).exists():
            print(f"Script {SCRIPTS_DIR / arg} not found")
            continue

        with open(SCRIPTS_DIR / arg) as script:
            commands = script.read().splitlines()
            for line in commands:
                exec_commands(line)


def guess_cmd(cmd, cmd_set):
    if cmd in cmd_set:
        return cmd
    commands = [c for c in cmd_set if c.startswith(cmd)]
    if len(commands) == 1:
        return commands[0]


def should_repeat():
    if not (music.get_busy() or Player.should_pause) and Player.repeats:
        Player.repeats -= 1
        return True


@command(Player)
def repeat(*args):
    cur_song = Path(Player.cur_song).stem
    if not cur_song:
        print("Nothing playing")
        return
    if not args:
        Player.repeats = 1
        print(f"{cur_song} will be repeated {Player.repeats} time.")
        return
    repeats = type_converter(args[0], int, "Repeats must be an integer")
    if not isinstance(repeats, int) or repeats < 0:
        print("Repeats must be at least 0")
        return
    Player.repeats = repeats
    print(f"{cur_song} will be repeated {Player.repeats} times.")


def clamp(num, low, high):
    return min(max(num, low), high)


def parse_input(string):
    commands = string.strip(";").split(";")
    # str.split is insufficient for our needs as we need to be able to parse
    # strings with spaces in them
    out = []
    accumulator = ""
    quoted = False
    for i, command in enumerate(commands):
        out.append([])
        for idx, ch in enumerate(command):
            if ch in ('"', "'"):
                quoted ^= True
            elif ch == " ":
                if quoted:
                    accumulator += ch
                elif accumulator:
                    out[i].append(accumulator.strip())
                    accumulator = ""
            else:
                accumulator += ch
        out[i].append(accumulator.strip())
        accumulator = ""
    return out


@command(Player, requires_args=True)
def play(*args):
    if len(args) >= 1:
        song = args[0]
    if len(args) >= 2:
        Player.volume = type_converter(
            args[1], float, "Volume needs to be between 0 and 100"
        )
    if len(args) >= 3:
        Player.loops = type_converter(
            args[2], int, "Number of loops must be an integer"
        )
    if Player.volume is None or Player.loops is None:
        return

    try:
        music.load(Settings.music_dir / song)
    except (pygame.error, FileNotFoundError):
        file = song
        song = ac_songs(Settings.autocomplete, song)
        if not song:
            return
        else:
            Player.playing_queue = False
            music.load(Settings.music_dir / song)
    if Settings.music_dir / song != Player.cur_song:
        Player.repeats = 0
    Player.cur_song = Settings.music_dir / song
    music.set_volume(Player.volume / 100)
    music.play(Player.loops)
    file = mutagen.File(Player.cur_song)
    Player.duration = file.info.length
    Player.loops = 0
    Player.offset = 0
    Player.should_pause = False


@command(Player)
def volume(*args):
    if not args:
        print(f"Volume: {Player.volume:.1f}%")
    elif len(args) == 1:
        increment = args[0][0] in ("+", "-")
        # Increment/decrement volume instead of setting to a new value
        new_volume = type_converter(
            args[0], float, "Volume needs to be between 0 and 100"
        )
        if not isinstance(new_volume, float):
            return
        if increment:
            Player.volume += new_volume
        else:
            Player.volume = new_volume
        Player.volume = clamp(Player.volume, 0.0, 100.0)
        music.set_volume(Player.volume / 100)


@command(Player)
def ls(*args):
    songs = gen_files()
    songs.sort()
    humanized = [song[: song.index(".")] for song in songs]
    print(Settings.ls_sep.join(humanized))


@command(Player, requires_args=True)
def find(*args):
    songs = gen_files()
    songs.sort()
    humanized = {song[: song.index(".")] for song in songs}

    for arg in args:
        songs = [song for song in humanized if song.startswith(arg)]
        print(f"{arg}: {Settings.ls_sep.join(songs)}")


@command(Player)
def loop(*args):
    if Player.loops > 0:
        Player.loops = 0
    Player.loops = ~Player.loops
    if Player.loops:
        print("Loop: on")
    else:
        print("Loop: off")
    start = music.get_pos() / 1000
    if music.get_busy() or Player.should_pause:
        music.pause()
        music.play(Player.loops, (start + Player.offset) % Player.duration)
        Player.offset += start
    if Player.should_pause:
        music.pause()


@command(Player)
def time(*args):
    if Player.duration == 0:
        print("Nothing playing")
        return
    cur_time = music.get_pos() / 1000 + Player.offset
    time = cur_time % Player.duration
    if not music.get_busy():
        if not Player.should_pause or (abs(time - Player.duration)) < 0.5:
            print("Nothing playing")
            return
    print(
        f"{timestamp(int(time))} elapsed, "
        f"{timestamp(int(Player.duration - time))} remaining"
    )


@command(Player, "rewind", requires_args=True)
def seek_relative(*args, forward=False):
    if not Player.duration:
        print("Nothing playing")
        return
    start = music.get_pos() / 1000 + Player.offset
    secs = args[0]
    try:
        float(secs)
    except ValueError:
        secs = timestamp_as_num(secs)
        if not secs:
            print("Expected either a number in seconds or a timestamp")
            return
    if not forward:
        time = clamp(float(secs), 0, start)
        Player.offset = new_time = start - time
    else:
        time = clamp(float(secs), 0, Player.duration - start - 0.1)
        Player.offset = new_time = start + time
    new_time %= Player.duration
    Player.offset %= Player.duration
    music.pause()
    music.play(Player.loops, new_time)
    if Player.should_pause:
        music.pause()


@command(Player, "seek", requires_args=True)
def seek_absolute(*args):
    if not Player.duration:
        print("Nothing playing")
        return
    time = args[0]
    try:
        float(time)
    except ValueError:
        time = timestamp_as_num(time)
        if not time:
            print("Expected either a number in seconds or a timestamp")
            return
    time = clamp(float(time), 0, Player.duration - 0.1)
    Player.offset = time
    music.pause()
    music.play(Player.loops, time)
    if Player.should_pause:
        music.pause()


@command(Player)
def pause(*args):
    Player.should_pause = not Player.should_pause
    if Player.should_pause:
        music.pause()
    else:
        music.unpause()


@command(Player)
def stop(*args):
    music.stop()
    music.unload()
    Player.cur_song = ""
    Player.playing_queue = False


@command(Player)
def unpause(*args):
    music.unpause()
    Player.should_pause = False


@command(Player, "exit")
def smp_exit(*args):
    music.unload()
    mixer.quit()
    exit(0)


def timestamp_as_num(ts):
    secs = 0
    hms = re.compile(r"^[1-9]{1,2}:[0-5][0-9]:[0-5][0-9]$")
    ms = re.compile(r"^[0-5][0-9]?:[0-5][0-9]$")
    if re.match(hms, ts) or re.match(ms, ts):
        ts = ts.split(":")
        ts.reverse()
        ts = list(map(int, ts))
        for idx, num in enumerate(ts):
            secs += num * (60**idx)
        return secs


def parse_and_execute(cmd, cmd_set):
    cmd = cmd.replace(";;", ";")
    commands = parse_input(cmd)
    for command in commands:
        cmd, *args = command
        for idx, arg in enumerate(args):
            if arg in Player.macros:
                args[idx] = Player.macros[arg]
        if not cmd:
            continue
        if cmd in cmd_set:
            cmd_set[cmd](*args)
        else:
            autocomplete(cmd, cmd_set, *args)


def stat_config(cfg_last_modified):
    cfg_mtime = CONFIG_PATH.stat().st_mtime
    if cfg_mtime != cfg_last_modified:
        reload_cfg(startup=False)  # Hot reloading
        return cfg_mtime
    return cfg_last_modified


def exec_commands(commands, visited=None):
    macros = Player.macros
    if visited is None:
        visited = set()
    args_list = []
    commands = list(map(str.strip, commands))
    for idx, cmd in enumerate(commands):
        cmd, *args = cmd.split()
        if command := guess_cmd(cmd, CMDS):
            # Make normal commands take precedence over macros
            args_list.append(" ".join((command.strip(), *args)))
        elif mcr := guess_cmd(cmd, macros):
            if mcr in visited:
                print("Recursive or cyclical macros are not allowed")
                return
            else:
                visited.add(mcr)
            commands[idx] = macros[mcr]
            # Whenever we see a macro, we need to expand it to actual
            # commands, then we feed it back into this function
            commands = "; ".join(commands).split(";")
            commands[idx] += f' {" ".join(args)}'
            return exec_commands(commands, visited)
            # Recursion allows macros of arbitrary depth
            # i.e. macros that call other macros that
            # call other macros ...
        else:
            autocomplete(cmd, CMDS, args)
    parse_and_execute("; ".join(args_list), CMDS)


@command(Player, requires_args=True)
def rename(*args):
    if len(args) % 2 != 0:
        print("Expected an even number of arguments")
        return
    for i in range(0, len(args), 2):
        first, second = args[i], args[i + 1]
        first = ac_songs(Settings.autocomplete, first)
        if not first:
            continue
        first_path = Settings.music_dir / first
        sfx = first_path.suffix
        second_path = (Settings.music_dir / second).with_suffix(sfx)
        first_path.rename(second_path)
        for file in Settings.playlist_dir.glob("*.csv"):
            with open(file, "r", newline="") as f:
                reader = csv.reader(f, delimiter=",")
                queue = next(iter(reader))
            if first in queue:
                queue[queue.index(first)] = second_path.name
                tmp = Player.queue.copy()
                Player.queue = queue
                q.save(file.with_suffix("").name)
                Player.queue = tmp
                del tmp


@command(Player, requires_args=True)
def delete(*args):
    for arg in args:
        song = ac_songs(Settings.autocomplete, arg)
        if not song:
            continue
        song_path = Settings.music_dir / song
        for file in Settings.playlist_dir.glob("*.csv"):
            with open(file, "r", newline="") as f:
                reader = csv.reader(f, delimiter=",")
                queue = next(iter(reader))
            if song in queue:
                queue.remove(song)
                tmp = Player.queue
                Player.queue = queue
                q.save(file.with_suffix("").name)
                Player.queue = tmp
                del tmp
        if song in Player.queue:
            parse_and_execute(f"queue remove {song}", CMDS)
    song_path.unlink()


def init(args):
    Settings.read_config(parser.get_config(CONFIG_PATH))
    Player.macros = macros.load_macros()
    Player.volume = Settings.default_volume
    mixer.init()
    exec_scripts(*map(Path, args))


def input_entered(user_input):
    while True:
        sleep(0.1)
        if Player.awaiting_commands:
            user_input[0] = input(Settings.prompt)


def main():
    for dir in (CONFIG_DIR, SCRIPTS_DIR):
        if not dir.exists():
            dir.mkdir(parents=True)
    user_input = [None]
    input_thread = Thread(target=input_entered, args=(user_input,))
    input_thread.daemon = True
    _, *args = argv
    failed_calls = 0
    clock = pygame.time.Clock()
    init(args)
    cfg_last_modified = CONFIG_PATH.stat().st_mtime
    input_thread.start()
    while True:
        try:
            cfg_last_modified = stat_config(cfg_last_modified)
            failed_calls = 0
        except FileNotFoundError:
            failed_calls += 1
            # Sometimes the config file is not recognized,
            # so we just need to wait.
            if failed_calls > 10000:
                print("CRITICAL: Config file not found!")
                config(generate=True)
                # Other times it really doesn't exist, likely because
                # it's been moved or deleted
            continue
        clock.tick(100)
        # Drastically reduces CPU usage with almost no performance hit
        if should_repeat() and Player.cur_song:
            # Fix bug where it would try to play immediately after being
            # stopped
            play(Player.cur_song)
        if q.should_advance():
            q.play()
        (command,) = user_input
        if command is None:
            continue
        elif not command or "\x0c" in command or "\t" in command:  # Ctrl-l
            pass
        else:
            cmd, *args = command.lower().split()
            if guess_cmd(cmd, CMDS) == "macro":
                CMDS["macro"](*args)  # Special case as splitting by ';' breaks
                # add_macro
            else:
                commands = " ".join((cmd, *args)).split(";")
                exec_commands(commands)
            user_input[0] = None


if __name__ == "__main__":
    main()
